---
- name: Install Ruby and Bundler
  hosts: all
  become: false
  tasks:
  - name: Install a list of packages
    apt:
      name: ['ruby-full', 'ruby-bundler', 'build-essential']
      state: present

