---
- name: Install Ruby & Bundler
  hosts: all
  become: true
  tasks:
  #Install all dependencies in a cycle
  - name: Install ruby and rubygems and required packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - ruby-full
      - ruby-bundler
      - build-essential
